name: cloud_nirvana
description: Portable abd Declarative Cloud.
version: 1.0.0
repository: https://github.com/corporatepiyush/cloud-nirvana

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  archive: 3.5.1
  async: 2.11.0
  characters: 1.3.0
  collection: 1.18.0
  convert: 3.1.1
  http: 1.2.1
  io: 1.0.4
  logging: 1.2.0
  path: 1.9.0
  quiver: 3.2.1

dev_dependencies:
  lints: ^4.0.0
  test: 1.24.0
